### ISSUE TITLE
"J" shape on Tetris.java

### ISSUE THREAD

**Issue by Pedr0liveira** [chocoteam/choco-geost#1]
In choco-geost/src/test/java/org/chocosolver/Tetris.java, in the "J" shape creation, I believe there are two swapped values:
In the line 219:

    private class J2 extends Shape {
        public J2() {
            offsets.add(new int[]{0, 0});
            boxes.add(new int[]{1, 3});
            offsets.add(new int[]{0, 1});
            boxes.add(new int[]{1, 1});
        }}

I believe this should be:

    private class J2 extends Shape {
        public J2() {
            offsets.add(new int[]{0, 0});
            boxes.add(new int[]{**3,1**});
            offsets.add(new int[]{0, 1});
            boxes.add(new int[]{1, 1});
        }} 

In the original creation, there would be 2 boxes on the same spot.
the same applies for the creation in the line 237.
Sorry if I'm wrong.
Thanks in advance, have a nice day!

**Comment by cprudhom** [comment]
You are right, thank you for finding the bug.
I'll update the code.

**Comment by cprudhom** [comment]
Pay attention: running TetrisTest will exhibit a known bug, that is not fixed yet (I can't figure out what goes wrong).
